---

- name: Create a new database with name 'glance'
  mysql_db:
    name: glance
    state: present
    login_user: root
    login_password: felina1602

- name: Install glance service and client
  apt:
    name: glance
    state: present

- name: Modify Glance Configuration
  ini_file:
    dest: /etc/glance/glance-api.conf
    section: database
    option: connection
    value: mysql+pymysql://root:felina1602@localhost/glance

- name: Configure Glance API
  ini_file:
    dest: /etc/glance/glance-api.conf
    section: '{{ item.section }}'
    option: '{{ item.option }}'
    value: '{{ item.value }}'
  with_items:
    - section: keystone_authtoken
      option: www_authenticate_uri
      value: http://controller:5000/
    - section: keystone_authtoken
      option: memcached_servers
      value: controller:11211
    - section: keystone_authtoken
      option: auth_url
      value: http://controller:5000/
    - section: keystone_authtoken
      option: auth_type
      value: password
    - section: keystone_authtoken
      option: project_domain_name
      value: Default
    - section: keystone_authtoken
      option: user_domain_name
      value: Default
    - section: keystone_authtoken
      option: project_name
      value: service
    - section: keystone_authtoken
      option: username
      value: glance
    - section: keystone_authtoken
      option: password
      value: felina1602
    - section: paste_deploy
      option: flavor
      value: keystone
    - section: glance_store
      option: stores
      value: file,http
    - section: glance_store
      option: filesystem_store_datadir
      value: /var/lib/glance/images/
    - section: glance_store
      option: default_store
      value: file

- name: Start Glance services
  service:
    enabled: True
    name: glance-api
    state: restarted
