---

- name: 1.1 Install MySQL
  apt: name={{ item }} update_cache=yes state=present
  with_items:
    - python3-mysql.connector
    - mysql-server

- name: 1.2 Start the MySQL service
  service:
    name: mysql
    state: started
    enabled: true

- name: 1.3 update mysql root password for all root accounts
  mysql_user:
    name: root
    host: "{{ item }}"
    password: felina1602
    login_user: root
    login_password: felina1602
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - 192.168.56.109    
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: 1.4 Create a new database with name 'keystone'
  mysql_db:
    name: keystone
    state: present
    login_user: root
    login_password: felina1602
    
- 


