---


- name: Create a new database with name 'nova'
  mysql_db:
    name: "{{ item }}"
    state: present
    login_user: root
    login_password: felina1602
  with_items:
    - nova_api
    - nova
    - nova cell0

- name: Install nova service and client
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - nova-api
    - nova-conductor
    - nova-novncproxy
    - nova-scheduler

- name: Modify Nova Configuration
  ini_file:
    dest: /etc/nova/nova.conf
    section: api_database
    option: connection
    value: mysql+pymysql://root:felina1602@localhost/nova_api

- name: Modify Nova Configuration
  ini_file:
    dest: /etc/nova/nova.conf
    section: database
    option: connection
    value: mysql+pymysql://root:felina1602@localhost/nova

- name: Configure Nova
  ini_file:
    dest: /etc/nova/nova.conf
    section: '{{ item.section }}'
    option: '{{ item.option }}'
    value: '{{ item.value }}'
  with_items:
    - section: keystone_authtoken
      option: www_authenticate_uri
      value: http://controller:5000/
    - section: keystone_authtoken
      option: memcached_servers
      value: controller:11211
    - section: keystone_authtoken
      option: auth_url
      value: http://controller:5000/
    - section: keystone_authtoken
      option: auth_type
      value: password
    - section: keystone_authtoken
      option: project_domain_name
      value: Default
    - section: keystone_authtoken
      option: user_domain_name
      value: Default
    - section: keystone_authtoken
      option: project_name
      value: service
    - section: keystone_authtoken
      option: username
      value: nova
    - section: keystone_authtoken
      option: password
      value: felina1602
    - section: DEFAULT
      option: my_ip
      value: 192.168.56.109
    - section: vnc
      option: enabled
      value: true
    - section: vnc
      option: service_listen
      value: $my_ip
    - section: vnc
      option: service_proxyclient_address
      value: $my_ip
    - section: glance
      option: api_servers
      value: http://controller:9292
    - section: oslo_concurrency
      option: lock_path
      value: /var/lib/nova/tmp

- name: Start Nova services
  service:
    enabled: True
    name: "{{ item }}"
    state: restarted
  with_items:
    - nova-api
    - nova-scheduler
    - nova-conductor
    - nova-novncproxy
